import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    display: "flex",
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#DBEAFC",
  },
  header: {
    position: "absolute",
    padding: 20,
    top: 50,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    zIndex: 1,
  },
  backBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#abbfda",
  },
  title: { color: "#6F7980", fontWeight: "bold" },
  nameWrapper: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#abbfda",
  },
  name: {
    color: "#6F7980",
    fontWeight: "bold",
    fontSize: 10,
  },
  textWrapper: {
    marginTop: -100,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  blobTop: {
    position: "absolute",
    top: 50,
    left: -100,
    width: 400,
    height: 600,
  },
  blobBottom: {
    position: "absolute",
    right: -20,
    bottom: 0,
    width: 350,
    height: 200,
  },
  plane: {
    marginTop: -100,
    width: "100%",
    objectFit: "contain",
    opacity: 0.75,
  },
  loadingCard: {
    position: "absolute",
    bottom: 30,
    width: "70%",
    objectFit: "contain",
    opacity: 0.75,
  },
  contentContainer: {
    position: "absolute",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 20,
  },
  loadingCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  loadingText: {
    color: "white",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 10,
  },
  subLoadingText: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 16,
  },
});
export default styles;
